spring:
  application:
    name: code-user
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CodeGeneration
    username: root
    password: root
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
#      激活本地环境
  profiles:
    active: local

server:
  port: 8977
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.liuh.codeuser.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# Dubbo
dubbo:
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 9977
  consumer:
    timeout: 60000
  provider:
    timeout: 60000
