spring:
  application:
    name: code-screenshot
#      激活本地环境
  profiles:
    active: local

server:
  port: 8979
  servlet:
    context-path: /api
logging:
  charset:
    console: utf-8
    file: UTF-8

# Dubbo
dubbo:
  registry:
    address: nacos://127.0.0.1:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 9979
  consumer:
    timeout: 120000
  provider:
    timeout: 120000
